version: 0.2

env:
  parameter-store:
    USERNAME: /myapp/docker-credentials/username
    PASSWORD: /myapp/docker-credentials/password
    KEY:  /myapp/api/key

        
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Verificando versión de Node.js"
      - node --version
    # steps:
  pre_build:
    commands:
      - echo "Autenticando en Docker Hub..."
      - docker login -u $USERNAME -p $PASSWORD
      - echo "Instalando dependencias..."
      - npm install
      - echo "Dependencias instaladas correctamente."
  build:
    commands:
      - echo "Construyendo imagen Docker..."
      - docker build . -t dhruvdarji123/netflix-react-app:latest --build-arg TMDB_V3_API_KEY=$KEY
  post_build:
    commands:
      - echo "Subiendo imagen a Docker Hub..."
      - docker push dhruvdarji123/netflix-react-app:latest
      - echo "Build completado exitosamente."
artifacts:
  files:
    - '**/*'
  base-directory: "./"
  name: build-artifact-name
  discard-paths: no
